### ISSUE TITLE
replace "x hit wtc" in the "!sux x" command

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ircbot#26]
We copied this from kochira, the old unofficial IRC bot that used to be in the channel, but it's in pretty poor taste and we should replace it.

Some possibilities:
* X is the worst
* X went to stanford
* X has outdated wordpress
* X voted for trump
* X called us "the ofc"
* X killed net neutrality
* X uses windows
* X caused a kernel panic

any other suggestions?

We don't necessarily need to pick just one; it'd be cool to have a list of lots of these and have each `!sux` invocation randomly pick 4 to use.

**Comment by Baisang** [comment]
X is bottom fragging
X hit their semesterly print quota
X called ABC news
X hotboxed the server room

**Comment by kpengboy** [comment]
X emailed us their password
X forgot to log out
X took down NFS
