### ISSUE TITLE
replacements trigger crash if the replacement string has a newline

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ircbot#3]

**Comment by gnowxilef** [comment]
also lol, 
![image](https://cloud.githubusercontent.com/assets/639565/22755042/605619cc-edf6-11e6-87f1-a6cb8c9d68f4.png)

**Comment by jvperrin** [comment]
I believe this is caused by [this line](https://github.com/jaraco/irc/blob/master/irc/client.py#L879) in the IRC client program we are using, so we just need to filter out newlines and it should work ok. Something like that anyway...
