### ISSUE TITLE
replacements trigger crash if the new message is too long

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ircbot#4]

**Comment by gnowxilef** [comment]
lol, how does that even happen?

**Comment by chriskuehl** [comment]
irc has a max line length, the library (correctly) raises an exception, we don't handle it

**Comment by gnowxilef** [comment]
i did not know that. 
![image](https://cloud.githubusercontent.com/assets/639565/22760716/83c1edf8-ee0c-11e6-9958-0f63cbfb0a84.png)

**Comment by jvperrin** [comment]
This works now as of https://github.com/ocf/ircbot/commit/7f7c8d9a64f96c9ce244144dad81c9105c6d54fa and https://github.com/ocf/ircbot/commit/836a957ddec2c56b5c593f2ff184ab318fc94841. I fixed it by just splitting the message across multiple `privmsg`s if it is too big, seems like it works, although calculating the length of the message is surprisingly tough.
